const DATE_CELLS_COUNT = 42;
const DATE_CELLS_IN_ROW_COUNT = 7;
const PERIOD_CELLS_IN_ROW_COUNT = 4;
const LEFT_PERIOD_PANEL_START_INDEX = 0;
const RIGHT_MONTH_PANEL_START_INDEX = 12;
const RIGHT_YEAR_PANEL_START_INDEX = 10;
const YEARS_IN_DECADE = 10;
const LAST_MONTH_IN_YEAR_INDEX = 11;
const LAST_YEAR_IN_DECADES_RANGE = 9;
const DAYS_IN_WEEK = 7;

export {
  DAYS_IN_WEEK,
  LAST_MONTH_IN_YEAR_INDEX,
  LAST_YEAR_IN_DECADES_RANGE,
  YEARS_IN_DECADE,
  DATE_CELLS_COUNT,
  DATE_CELLS_IN_ROW_COUNT,
  PERIOD_CELLS_IN_ROW_COUNT,
  LEFT_PERIOD_PANEL_START_INDEX,
  RIGHT_MONTH_PANEL_START_INDEX,
  RIGHT_YEAR_PANEL_START_INDEX
};
